
package uk.ac.ebi.demo.picr.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 09:55 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AccessionMapperInterface", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccessionMapperInterface {


    /**
     * 
     * @param taxonId
     * @param onlyActive
     * @param sequence
     * @param searchDatabases
     * @return
     *     returns uk.ac.ebi.demo.picr.soap.UPEntry
     */
    @WebMethod(action = "getUPIForSequence")
    @WebResult(name = "getUPIForSequenceReturn", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
    @RequestWrapper(localName = "getUPIForSequence", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService", className = "uk.ac.ebi.demo.picr.soap.GetUPIForSequence")
    @ResponseWrapper(localName = "getUPIForSequenceResponse", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService", className = "uk.ac.ebi.demo.picr.soap.GetUPIForSequenceResponse")
    public UPEntry getUPIForSequence(
        @WebParam(name = "sequence", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
        String sequence,
        @WebParam(name = "searchDatabases", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
        List<String> searchDatabases,
        @WebParam(name = "taxonId", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
        String taxonId,
        @WebParam(name = "onlyActive", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
        boolean onlyActive);

    /**
     * 
     * @param taxonId
     * @param onlyActive
     * @param blastParameters
     * @param identityTaxon
     * @param sequence
     * @param searchDatabases
     * @param identityValue
     * @param filterType
     * @param blastDB
     * @return
     *     returns java.util.List<uk.ac.ebi.demo.picr.soap.UPEntry>
     */
    @WebMethod(action = "getUPIForBlastSequence")
    @WebResult(name = "getUPIForBlastSequenceReturn", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
    @RequestWrapper(localName = "getUPIForBlastSequence", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService", className = "uk.ac.ebi.demo.picr.soap.GetUPIForBlastSequence")
    @ResponseWrapper(localName = "getUPIForBlastSequenceResponse", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService", className = "uk.ac.ebi.demo.picr.soap.GetUPIForBlastSequenceResponse")
    public List<UPEntry> getUPIForBlastSequence(
        @WebParam(name = "sequence", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
        String sequence,
        @WebParam(name = "searchDatabases", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
        List<String> searchDatabases,
        @WebParam(name = "identityValue", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
        String identityValue,
        @WebParam(name = "identityTaxon", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
        String identityTaxon,
        @WebParam(name = "filterType", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
        String filterType,
        @WebParam(name = "blastDB", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
        String blastDB,
        @WebParam(name = "taxonId", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
        String taxonId,
        @WebParam(name = "onlyActive", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
        boolean onlyActive,
        @WebParam(name = "blastParameters", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
        BlastParameter blastParameters);

    /**
     * 
     * @param taxonId
     * @param onlyActive
     * @param acVersion
     * @param accession
     * @param searchDatabases
     * @return
     *     returns java.util.List<uk.ac.ebi.demo.picr.soap.UPEntry>
     */
    @WebMethod(action = "getUPIForAccession")
    @WebResult(name = "getUPIForAccessionReturn", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
    @RequestWrapper(localName = "getUPIForAccession", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService", className = "uk.ac.ebi.demo.picr.soap.GetUPIForAccession")
    @ResponseWrapper(localName = "getUPIForAccessionResponse", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService", className = "uk.ac.ebi.demo.picr.soap.GetUPIForAccessionResponse")
    public List<UPEntry> getUPIForAccession(
        @WebParam(name = "accession", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
        String accession,
        @WebParam(name = "ac_version", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
        String acVersion,
        @WebParam(name = "searchDatabases", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
        List<String> searchDatabases,
        @WebParam(name = "taxonId", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
        String taxonId,
        @WebParam(name = "onlyActive", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
        boolean onlyActive);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(action = "getMappedDatabaseNames")
    @WebResult(name = "mappedDatabases", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService")
    @RequestWrapper(localName = "getMappedDatabaseNames", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService", className = "uk.ac.ebi.demo.picr.soap.GetMappedDatabaseNames")
    @ResponseWrapper(localName = "getMappedDatabaseNamesResponse", targetNamespace = "http://www.ebi.ac.uk/picr/AccessionMappingService", className = "uk.ac.ebi.demo.picr.soap.GetMappedDatabaseNamesResponse")
    public List<String> getMappedDatabaseNames();

}
