name: build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        cache: maven
    - name: Build with Maven
      run: mvn clean install -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.test.failure.ignore=true -Dproject.build.sourceEncoding=UTF-8 -Djunit5.excludeGroups=webservice,mysql
    - name: push JaCoCo stats to codecov.io
      uses: codecov/codecov-action@v4
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
